# Build Docker image for this app using Azure Pipelines
# http://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  image: '$(image_name):$(Build.BuildId)'
  # define two more variables dockerId and dockerPassword in the build pipeline in UI

steps:
- script: |
    #dotnet build --configuration $(buildConfiguration)
    #dotnet test dotnetcore-tests --configuration $(buildConfiguration) --logger trx
    #dotnet publish --configuration $(buildConfiguration) --output out
    docker build -t $(acr_name).azurecr.io/$(image) ./MicroService.Api
    docker login -u $(acr_name) -p $pswd $(acr_name).azurecr.io
    docker push $(acr_name).azurecr.io/$(image)

  env:
    pswd: $(acr_password)

- task: CopyFiles@2
  inputs:
    SourceFolder: 'Terraform'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: Artifacts
