# Build container image for this app using Azure Pipelines
# http://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'

#steps:
#  inputs:
#    azureSubscription: 'Azure-Subscription'
#- script: |
#    az acr login --name $(acr_name) --password $(acr_password)
#    az acr build --registry $(acr_name) --image $(image_name):$(Build.BuildId) .

steps:
- task: AzureCLI@1
  displayName: 'Azure CLI'
  inputs:
    azureSubscription: 'Azure-Connection-Endpoint'
    scriptLocation: inlineScript
    inlineScript: 'az acr build --registry $(acr_name) --image $(image_name):$(Build.BuildId) .'