# Build container image for this app using Azure Pipelines
# http://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: az acr build --registry $(acr_name) --image $(image_name):$(Build.BuildId) .